require 'json'

testjsonglobal = '[{"response": {"created_at": "2013-11-23T13:05:03",
               "id": 1,
               "lesson_id": 1,
               "lesson_name": "",
               "question_id": -1,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 4,
               "user_name": "Student D",
               "value": ""}},
 {"response": {"created_at": "2013-11-23T13:06:01",
               "id": 1,
               "lesson_id": -1,
               "lesson_name": "",
               "question_id": -1,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 5,
               "user_name": "Student E",
               "value": ""}},
 {"response": {"created_at": "2013-11-23T13:07:57",
               "id": 1,
               "lesson_id": -1,
               "lesson_name": "",
               "question_id": -1,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 1,
               "user_name": "Student A",
               "value": ""}},
 {"response": {"created_at": "2013-11-23T13:11:03",
               "id": 1,
               "lesson_id": -1,
               "lesson_name": "",
               "question_id": -1,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 2,
               "user_name": "Student B",
               "value": ""}},
 {"response": {"created_at": "2013-11-23T13:13:19",
               "id": 1,
               "lesson_id": -1,
               "lesson_name": "",
               "question_id": -1,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 3,
               "user_name": "Student C",
               "value": ""}},
 {"response": {"created_at": "2013-11-23T13:15:03",
               "id": 4,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 1,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 4,
               "user_name": "Student D",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T13:17:12",
               "id": 23,
               "lesson_id": 3,
               "lesson_name": "Lesson 3",
               "question_id": 5,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 3,
               "user_name": "Student C",
               "value": "Answer for Lesson 3, Q3"}},
 {"response": {"created_at": "2013-11-23T13:18:26",
               "id": 25,
               "lesson_id": 3,
               "lesson_name": "Lesson 3",
               "question_id": 5,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 5,
               "user_name": "Student E",
               "value": "Answer for Lesson 3, Q3"}},
 {"response": {"created_at": "2013-11-23T13:19:26",
               "id": 24,
               "lesson_id": 3,
               "lesson_name": "Lesson 3",
               "question_id": 5,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 5,
               "user_name": "Student E",
               "value": "Answer for Lesson 3, Q3"}},
 {"response": {"created_at": "2013-11-23T13:19:58",
               "id": 5,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 1,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 5,
               "user_name": "Student E",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T13:27:15",
               "id": 20,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 4,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 1,
               "user_name": "Student A",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T13:28:17",
               "id": 21,
               "lesson_id": 3,
               "lesson_name": "Lesson 3",
               "question_id": 5,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 3,
               "user_name": "Student C",
               "value": "Answer for Lesson 3, Q3"}},
 {"response": {"created_at": "2013-11-23T13:29:06",
               "id": 27,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 6,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 1,
               "user_name": "Student A",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T13:32:17",
               "id": 29,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 6,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 4,
               "user_name": "Student D",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T13:33:08",
               "id": 9,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 2,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 5,
               "user_name": "Student E",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T13:42:45",
               "id": 26,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 6,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 2,
               "user_name": "Student B",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T13:43:20",
               "id": 13,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 3,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 4,
               "user_name": "Student D",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T13:45:04",
               "id": 18,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 4,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 4,
               "user_name": "Student D",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T13:49:20",
               "id": 2,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 1,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 4,
               "user_name": "Student D",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T13:50:54",
               "id": 3,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 1,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 2,
               "user_name": "Student B",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T13:51:47",
               "id": 19,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 4,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 4,
               "user_name": "Student D",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T13:52:01",
               "id": 15,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 3,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 4,
               "user_name": "Student D",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T13:52:20",
               "id": 12,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 3,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 5,
               "user_name": "Student E",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T13:55:41",
               "id": 22,
               "lesson_id": 3,
               "lesson_name": "Lesson 3",
               "question_id": 5,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 2,
               "user_name": "Student B",
               "value": "Answer for Lesson 3, Q3"}},
 {"response": {"created_at": "2013-11-23T13:55:56",
               "id": 11,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 3,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 5,
               "user_name": "Student E",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T13:57:46",
               "id": 16,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 4,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 3,
               "user_name": "Student C",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T13:58:24",
               "id": 8,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 2,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 1,
               "user_name": "Student A",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T13:58:36",
               "id": 1,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 1,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 3,
               "user_name": "Student C",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T14:01:09",
               "id": 6,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 2,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 5,
               "user_name": "Student E",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T14:01:37",
               "id": 10,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 2,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 2,
               "user_name": "Student B",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T14:06:08",
               "id": 14,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 3,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 5,
               "user_name": "Student E",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T14:09:21",
               "id": 28,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 6,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 5,
               "user_name": "Student E",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T14:11:01",
               "id": 17,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 4,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 5,
               "user_name": "Student E",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T14:13:54",
               "id": 7,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 2,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 1,
               "user_name": "Student A",
               "value": "Answer for Lesson 1, Q1"}},
 {"response": {"created_at": "2013-11-23T14:14:13",
               "id": 30,
               "lesson_id": 1,
               "lesson_name": "Lesson 1",
               "question_id": 6,
               "updated_at": "2013-11-23T16:37:52-08:00",
               "user_id": 1,
               "user_name": "Student A",
               "value": "Answer for Lesson 1, Q1"}}]'

get '/' do
  @students=User.where(role: "student")
  @questions = Question.all
  @responses = Response.all
  @lessons= Lesson.all

  # if xhr
  #   content_type :json

  #   return @responses.to_json
  # # end
    erb :index
end

get '/sa_responses' do

     responses = Response.includes(:user, :question)

     expanded_reponse = responses.map do |r|
          {response: {user_id: r.user_id, 
          first_name: r.user.first_name, 
          last_name: r.user.last_name, 
          question_id: r.question_id,
          question_text: r.question.text, 
          value: r.value,
          created_at: r.created_at,
          created_at_epoch: r.created_at.to_i}}
     end

     p expanded_reponse.to_json
end

get '/responses' do

   @responses = Response.all

  # if xhr
   content_type :json
  @responses.to_json
  # end
 
end

get '/questions' do

  @questions = Question.all
  content_type :json
  @questions.to_json
 
end

get '/students' do

  @students = User.where(role: "student")
  content_type :json
  @students.to_json
 
end

get '/test' do
  erb :test
end

get '/responses1' do
  testjson = JSON.parse(testjsonglobal)
  content_type :json
  testjson = testjson.map { |x| x["response"] }
  testjson.to_json

end
